# Generated by Django 5.1.7 on 2025-11-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('current_scene', models.CharField(default='start', max_length=100)),
                ('inventory', models.JSONField(default=list)),
                ('visited_scenes', models.JSONField(default=list)),
                ('game_flags', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game State',
                'verbose_name_plural': 'Game States',
            },
        ),
    ]
